algo: sac
algo_config:
  activation: relu
  actor_lr: 0.00045196308120485273
  clip_obs: 10.0
  clip_reward: 10.0
  critic_lr: 0.022547326782152065
  deque_size: 10
  entropy_lr: 0.001
  eval_batch_size: 10
  eval_interval: 500
  eval_save_best: true
  gamma: 0.98
  hidden_dim: 256
  init_temperature: 0.2
  log_interval: 500
  max_buffer_size: 50000
  max_env_steps: 50000
  norm_obs: false
  norm_reward: false
  num_checkpoints: 0
  num_workers: 1
  rollout_batch_size: 4
  save_interval: 0
  target_entropy: null
  tau: 0.12145208815621376
  tensorboard: false
  train_batch_size: 512
  train_interval: 100
  training: true
  use_entropy_tuning: false
  warm_up_steps: 100
device: cpu
kv_overrides:
- task_config.randomized_init=True
output_dir: ./sac_data/0/
overrides:
- ./config_overrides/cartpole/sac_cartpole.yaml
- ./config_overrides/cartpole/cartpole_stab.yaml
restore: null
seed: 0
tag: temp
task: cartpole
task_config:
  adversary_disturbance: null
  adversary_disturbance_offset: 0.0
  adversary_disturbance_scale: 0.01
  constraint_penalty: -10.0
  constraints:
  - constrained_variable: state
    constraint_form: default_constraint
    lower_bounds:
    - -10
    - -10
    - -0.2
    - -0.2
    upper_bounds:
    - 10
    - 10
    - 0.2
    - 0.2
  - constrained_variable: input
    constraint_form: default_constraint
    lower_bounds:
    - -10
    upper_bounds:
    - 10
  cost: rl_reward
  ctrl_freq: 15
  disturbances:
    observation:
    - disturbance_func: white_noise
      std: 0.0001
  done_on_out_of_bound: false
  done_on_violation: false
  episode_len_sec: 5
  gui: false
  inertial_prop:
    cart_mass: 1
    pole_length: 0.5
    pole_mass: 0.1
  inertial_prop_randomization_info: null
  info_in_reset: true
  init_state:
    init_theta: 0.0
    init_theta_dot: 0.0
    init_x: 0.5
    init_x_dot: 0.0
  init_state_randomization_info:
    init_theta:
      distrib: uniform
      high: 0.05
      low: -0.05
    init_theta_dot:
      distrib: uniform
      high: 0.05
      low: -0.05
    init_x:
      distrib: uniform
      high: 0.0
      low: 0.0
    init_x_dot:
      distrib: uniform
      high: 0.05
      low: -0.05
  normalized_rl_action_space: true
  obs_goal_horizon: 0
  obs_wrap_angle: false
  physics: pyb
  pyb_freq: 750
  randomized_inertial_prop: false
  randomized_init: true
  rew_act_weight: 0.1
  rew_exponential: true
  rew_state_weight:
  - 1
  - 0.1
  - 1
  - 0.1
  seed: 42
  task: stabilization
  task_info:
    stabilization_goal:
    - 0.0
    - 0
    stabilization_goal_tolerance: 0.0
  use_constraint_penalty: false
  verbose: false
use_gpu: false
