algo: ppo
algo_config:
  activation: relu
  actor_lr: 0.001
  clip_obs: 10
  clip_param: 0.2
  clip_reward: 10
  critic_lr: 0.001
  deque_size: 10
  entropy_coef: 0.01
  eval_batch_size: 10
  eval_interval: 2000
  eval_save_best: true
  gae_lambda: 0.95
  gamma: 0.99
  hidden_dim: 128
  log_interval: 2000
  max_env_steps: 200000
  max_grad_norm: 0.5
  mini_batch_size: 256
  norm_obs: false
  norm_reward: false
  num_checkpoints: 0
  num_workers: 1
  opt_epochs: 20
  rollout_batch_size: 4
  rollout_steps: 1000
  save_interval: 0
  target_kl: 0.01
  tensorboard: false
  training: true
  use_clipped_value: false
  use_gae: true
device: cpu
kv_overrides:
- task_config.randomized_init=True
output_dir: ./ppo_data/0/
overrides:
- ./config_overrides/quadrotor_2D_attitude/ppo_quadrotor_2D_attitude.yaml
- ./config_overrides/quadrotor_2D_attitude/quadrotor_2D_attitude_track.yaml
restore: null
seed: 0
tag: temp
task: quadrotor
task_config:
  adversary_disturbance: null
  adversary_disturbance_offset: 0.0
  adversary_disturbance_scale: 0.01
  constraint_penalty: -1
  constraints:
  - constrained_variable: state
    constraint_form: default_constraint
    lower_bounds:
    - -2
    - -1
    - 0
    - -1
    - -0.2
    upper_bounds:
    - 2
    - 1
    - 2
    - 1
    - 0.2
  - constrained_variable: input
    constraint_form: default_constraint
    lower_bounds:
    - 0.06
    - -0.8
    upper_bounds:
    - 0.58
    - 0.8
  cost: rl_reward
  ctrl_freq: 60
  disturbances: null
  done_on_out_of_bound: false
  done_on_violation: false
  episode_len_sec: 10
  gui: false
  inertial_prop:
    Iyy: 1.4e-05
    M: 0.027
  inertial_prop_randomization_info: null
  info_in_reset: true
  init_state:
    init_theta: 0
    init_x: 0
    init_x_dot: 0
    init_z: 1.15
    init_z_dot: 0
  init_state_randomization_info:
    init_theta:
      distrib: uniform
      high: 0.02
      low: -0.02
    init_x:
      distrib: uniform
      high: 0.01
      low: -0.01
    init_x_dot:
      distrib: uniform
      high: 0.01
      low: -0.01
    init_z:
      distrib: uniform
      high: 1.15
      low: 1.15
    init_z_dot:
      distrib: uniform
      high: 0.01
      low: -0.01
  norm_act_scale: 0.1
  normalized_rl_action_space: false
  obs_goal_horizon: 1
  physics: pyb
  pyb_freq: 1200
  quad_type: 4
  randomized_inertial_prop: false
  randomized_init: true
  rew_act_weight: 2.0
  rew_exponential: true
  rew_state_weight:
  - 10.0
  - 1.0
  - 10.0
  - 1.0
  - 1.0
  seed: 1337
  task: traj_tracking
  task_info:
    num_cycles: 1
    trajectory_plane: xz
    trajectory_position_offset:
    - 0
    - 1.2
    trajectory_scale: 0.5
    trajectory_type: figure8
  use_constraint_penalty: false
  verbose: false
use_gpu: false
